language: ruby
script: bundle exec cucumber
rvm:
- ruby-head
- jruby-head
- jruby-19mode
- 2.2
- 2.1
- 2.0
- 1.9.3
os:
- linux
- osx
env: TEST=true TRAVIS=true
gemfile:
- Gemfile
notifications:
  slack:
    secure: C8xb94J4fstzAI7t9GcvKQieKc1k+ECA96ydcxDwBI1fAbupQjz4jafMwnOnD1g9QMe8hlykSNUlCXNCbcA9DZG7COjPZHCY3Icv1+0Dp44bBTDQldR8DPACPMU5Qe+pWoTZViPgJQ7tq2V9TXrGdOnOtkPTwZ9KtZrmNhxW7tM=
